Fixed to use proper prefix
git-svn-id: file:///work/internal/svn/package_builder@1578 f6b31dc6-dd17-0410-bcf4-f92f679a180a

diff --git a/build_rootfs b/build_rootfs
--- a/build_rootfs
+++ b/build_rootfs
@@ -33,7 +33,12 @@ copy_lib () {
 
 install_package() {
     package=$1
-    ar p ${PACKAGE_DIR}/${package}_*.ipk data.tar.gz | (cd $DEST ; tar xz)
+    FILE="${PACKAGE_DIR}/${package}_*.ipk"
+    if [ ! -f ${FILE} ] ; then
+        echo "Cannot find package '${package}'" >&2
+        exit 1
+    fi
+    ar p ${FILE} data.tar.gz | (cd $DEST ; tar xmz)
     echo -n "."
 }
 
